### ISSUE TITLE
Roadmap to training

### ISSUE THREAD

**Issue by wenkokke** [vehicle-lang/vehicle#810]
**Python backend**

- [x] Add meet/join to minimize/maximize
- [x] Add context to minimize/maximize
- [x] Add PGD as default optimization strategy, from implementation on `old-pgd` branch
- [x] Fix `windController` and `mnistRobustness` examples unnecessarily expanding `fold`

**Comment by MatthewDaggitt** [comment]
This was fixed in https://github.com/vehicle-lang/vehicle/pull/1003
